openapi: 3.0.0
servers:
  - description: Cluster Endpoint
    url: /api
info:
  description: Consulting List management for Web-In-Cloud system
  version: "1.0.0"
  title: Waiting List Api
  contact:
    email: xtodorovic@stuba.sk
  license:
    name: CC BY 4.0
    url: "https://creativecommons.org/licenses/by/4.0/"
tags:
- name: consultations
  description: Consulting 


paths:
  "/requests-list/{requestId}/entries":
    get:
      tags:
        - consultations
      summary: Provides the requests list
      operationId: getRequestsListEntries
      description: By using requestId you get list of entries in ambulance waiting list
      parameters:
        - in: path
          name: requestId
          description: pass the id of the particular request
          required: true
          schema:
            type: string
      responses:
        "200":
          description: value of the list entries
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/WaitingListEntry"
              examples:
                response:
                  $ref: "#/components/examples/WaitingListEntriesExample"
        "404":
          description: Ambulance with such ID does not exist

  "/consulting-form":
    post:
      tags:
        - consultations
      summary: Submit a new consultation request
      operationId: submitConsultingForm
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ConsultingForm'
            examples:
              sample:
                value:
                  name: John Doe
                  email: john@example.com
                  symptoms: Fatigue and nausea
      responses:
        "201":
          description: Consultation request successfully submitted
        "400":
          description: Invalid input

  "/consultation-form/{requestId}":
    patch:
      tags:
        - consultations
      summary: Update consultation with time and video link
      operationId: updateConsultation
      parameters:
        - in: path
          name: requestId
          required: true
          description: ID of the consultation request
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ConsultationUpdate"
            examples:
              example:
                value:
                  scheduledDate: "2025-06-01"
                  scheduledTime: "14:30"
                  videoLink: "https://meet.example.com/xyz123"
      responses:
        "200":
          description: Consultation successfully updated
        "404":
          description: Consultation not found
        "400":
          description: Invalid data
  "/consultation-form/{requestId}/delete":
    delete:
      tags:
        - consultations
      summary: Delete consultation
      operationId: deleteConsultation
      parameters:
        - in: path
          name: requestId
          required: true
          description: ID of the consultation request
          schema:
            type: string
      responses:
        "204":
          description: Consultation successfully deleted
        "404":
          description: Consultation not found

components:
  schemas:
    ConsultationUpdate:
      type: object
      required:
        - id
        - scheduledDate
        - scheduledTime
        - videoLink
      properties:
        id:
          type: string
          example: "12345"
          description: Unique identifier of the consultation request
        scheduledDate:
          type: string
          format: date
          example: "2025-06-01"
        scheduledTime:
          type: string
          pattern: "^([0-1]?[0-9]|2[0-3]):[0-5][0-9]$"
          example: "14:30"
        videoLink:
          type: string
          format: uri
          example: "https://meet.example.com/xyz123"
    ConsultingForm:
      type: object
      required:
        - id
        - name
        - email
        - symptoms
      properties:
        id:
          type: string
          example: "12345"
          description: Unique identifier for the consultation request
        name:
          type: string
          example: John Doe
        email:
          type: string
          format: email
          example: john@example.com
        symptoms:
          type: string
          example: Persistent headache and dizziness
    WaitingListEntry:
      type: object
      required: [id, patientId, waitingSince, estimatedDurationMinutes]
      properties:
        id:
          type: string
          example: x321ab3
          description: Unique id of the entry in this waiting list
        name:
          type: string
          example: Jožko Púčik
          description: Name of patient in waiting list
        patientId:
          type: string
          example: 460527-jozef-pucik
          description: Unique identifier of the patient known to Web-In-Cloud system
        waitingSince:
          type: string
          format: date-time
          example: "2038-12-24T10:05:00Z"
          description: Timestamp since when the patient entered the waiting list
        estimatedStart:
          type: string
          format: date-time
          example: "2038-12-24T10:35:00Z"
          description: Estimated time of entering ambulance. Ignored on post.
        estimatedDurationMinutes:
          type: integer
          format: int32
          example: 15
          description: >-
            Estimated duration of ambulance visit. If not provided then it will
            be computed based on condition and ambulance settings
        condition:
          $ref: "#/components/schemas/Condition"
      example:
        $ref: "#/components/examples/WaitingListEntryExample"
    Condition:
      description: "Describes disease, symptoms, or other reasons of patient   visit"
      required:
        - value
      properties:
        value:
          type: string
          example: Teploty
        code:
          type: string
          example: subfebrilia
        reference:
          type: string
          format: url
          example: "https://zdravoteka.sk/priznaky/zvysena-telesna-teplota/"
          description: Link to encyclopedical explanation of the patient's condition
        typicalDurationMinutes:
          type: integer
          format: int32
          example: 20
      example:
        $ref: "#/components/examples/ConditionExample"
  examples:
    WaitingListEntryExample:
      summary: Ľudomír Zlostný waiting
      description: |
        Entry represents a patient waiting in the ambulance prep room with
        defined symptoms
      value:
        id: x321ab3
        name: Ľudomír Zlostný
        patientId: 74895-ludomir-zlostny
        waitingSince: "2038-12-24T10:05:00.000Z"
        estimatedStart: "2038-12-24T10:35:00.000Z"
        estimatedDurationMinutes: 15
        condition:
          value: Nevoľnosť
          code: nausea
          reference: "https://zdravoteka.sk/priznaky/nevolnost/"
    ConditionExample:
      summary: Conditions and symptoms
      description: list of few symptoms that can be chosen by patients
      value:
        valuee: Teploty
        code: subfebrilia
        reference: >-
          https://zdravoteka.sk/priznaky/zvysena-telesna-teplota/
    WaitingListEntriesExample:
      summary: List of waiting patients
      description: |
        Example waiting list containing 2 patients
      value:
      - id: x321ab3
        name: Jožko Púčik
        patientId: 460527-jozef-pucik
        waitingSince: "2038-12-24T10:05:00.000Z"
        estimatedStart: "2038-12-24T10:35:00.000Z"
        estimatedDurationMinutes: 15
        condition:
          value: Teploty
          code: subfebrilia
          reference: "https://zdravoteka.sk/priznaky/zvysena-telesna-teplota/"
      - id: x321ab4
        name: Ferdinand Trety
        patientId: 780907-ferdinand-tre
        waitingSince: "2038-12-24T10:25:00.000Z"
        estimatedStart: "2038-12-24T10:50:00.000Z"
        estimatedDurationMinutes: 25
        condition:
          value: Nevoľnosť
          code: nausea
          reference: "https://zdravoteka.sk/priznaky/nevolnost/"